### ISSUE TITLE
How could I solve "tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU"

### ISSUE THREAD

**Issue by Celeste-cj** [isarandi/metro-pose3d#1] opened 2020-03-30 08:08 UTC

**Comment by isarandi** [comment] 2020-03-30 08:28
I'm still investigating the cause of this, perhaps I'll switch to NHWC order.

Either way, the prediction works correctly for me, despite the error message.

**Comment by isarandi** [comment] 2020-03-31 04:23
Fixed by switching to NHWC order for the exported models (although I think it was a harmless warning/error).

**Closed as completed by isarandi** 2020-03-31 04:23 UTC
